### ISSUE TITLE
Exception on setting fileName and path

### ISSUE THREAD

**Issue by DeepikaKochar** [triniwiz/nativescript-downloader#21]
### Which platform(s) does your issue occur on?
- Android emulator(Not tested on iOS)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.0.2
- Cross-platform modules: 4.0.1
- Runtime(s):"tns-android": {
      "version": "4.0.1"
    }
- Plugin(s): 
 "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "base-64": "^0.1.0",
    "nativescript-angular": "~5.3.0",
    "nativescript-downloader": "^2.0.0",
    "nativescript-drop-down": "^3.1.3",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-plugin-firebase": "^6.1.0",
    "nativescript-pro-ui": "^3.4.1",
    "nativescript-snackbar": "^3.1.0",
    "nativescript-social-login": "^4.0.0",
    "nativescript-social-share": "^1.4.0",
    "nativescript-sqlite": "^2.2.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-webview-interface": "^1.4.1",
    "nativescript-xml2js": "^0.5.2",
    "nativescript-zip": "^1.3.2",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~5.5.5",
    "tns-core-modules": "~4.0.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.7.0",
    "typescript": "~2.7.2"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 
Whenever I try to pass fileName and path to createDownload method I receive this Exception : 

```
An uncaught Exception occurred on "OkHttp Dispatcher" thread.
java.lang.StringIndexOutOfBoundsException: length=7; index=-1
	at java.lang.String.substring(String.java:1893)
	at co.fitcom.fancydownloader.ManagerService$1$1.onResponse(ManagerService.java:114)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

### Is there any code involved? 
           ```
 var downloadId = this.downloader.createDownload({
			url: url,
			path: this.fileservice.getImageFolderPath(),
			fileName: fileName
		});
		console.log(`File Id :${downloadId} `);
		this.downloader.start(downloadId, (progressData: ProgressEventData) => {
			console.log(progressData.value);
		}).then(downloaderResponse => {
			console.log("completed "+JSON.stringify(downloaderResponse));
		}).catch(error => {
			console.log("error in downloading "+JSON.stringify(error));
		});.

```

**Comment by triniwiz** [comment]
What does the path and file name look like ?


Sent from Yahoo Mail for iPhone


On Monday, June 11, 2018, 1:06 AM, DeepikaKochar <notifications@github.com> wrote:


Which platform(s) does your issue occur on?
   
   - Android emulator(Not tested on iOS)

Please, provide the following version numbers that your issue occurs with:
   
   - CLI: 4.0.2
   - Cross-platform modules: 4.0.1
   - Runtime(s):"tns-android": {   
"version": "4.0.1"   
}
   - Plugin(s):   
"dependencies": {   
" ": "~5.2.0",   
" ": "~5.2.0",   
" ": "~5.2.0",   
" ": "~5.2.0",   
" ": "~5.2.0",   
" ": "~5.2.0",   
" ": "~5.2.0",   
" ": "~5.2.0",   
" ": "~5.2.0",   
"base-64": "^0.1.0",   
"nativescript-angular": "~5.3.0",   
"nativescript-downloader": "^2.0.0",   
"nativescript-drop-down": "^3.1.3",   
"nativescript-pdf-view": "^2.0.1",   
"nativescript-plugin-firebase": "^6.1.0",   
"nativescript-pro-ui": "^3.4.1",   
"nativescript-snackbar": "^3.1.0",   
"nativescript-social-login": "^4.0.0",   
"nativescript-social-share": "^1.4.0",   
"nativescript-sqlite": "^2.2.1",   
"nativescript-theme-core": "~1.0.4",   
"nativescript-toast": "^1.4.6",   
"nativescript-webview-interface": "^1.4.1",   
"nativescript-xml2js": "^0.5.2",   
"nativescript-zip": "^1.3.2",   
"reflect-metadata": "~0.1.10",   
"rxjs": "~5.5.5",   
"tns-core-modules": "~4.0.0",   
"zone.js": "~0.8.18"   
},   
"devDependencies": {   
"babel-traverse": "6.4.5",   
"babel-types": "6.4.5",   
"babylon": "6.4.5",   
"lazy": "1.0.11",   
"nativescript-dev-typescript": "~0.7.0",   
"typescript": "~2.7.2"   
}

Please, tell us how to recreate the issue in as much detail as possible.

Whenever I try to pass fileName and path to createDownload method I receive this Exception :
An uncaught Exception occurred on "OkHttp Dispatcher" thread.
java.lang.StringIndexOutOfBoundsException: length=7; index=-1
	at java.lang.String.substring(String.java:1893)
	at co.fitcom.fancydownloader.ManagerService$1$1.onResponse(ManagerService.java:114)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

Is there any code involved?
       ```

var downloadId = this.downloader.createDownload({
url: url,
path: this.fileservice.getImageFolderPath(),
fileName: fileName
});
console.log(File Id :${downloadId});
this.downloader.start(downloadId, (progressData: ProgressEventData) => {
console.log(progressData.value);
}).then(downloaderResponse => {
console.log("completed "+JSON.stringify(downloaderResponse));
}).catch(error => {
console.log("error in downloading "+JSON.stringify(error));
});.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by DeepikaKochar** [comment]
path:  '/data/user/0/BUNDLE.ID/fancy_downloader/'
fileName:  'courseimage_20180608115442000000.jpg'

**Comment by yringler** [comment]
I'm having this same issue.
Install on a real device, using angular.
Path: /data/user/0/org.nativescript.RabbiGordonAudio/files
filename: 0rdon1553774400

In my exception, the string length was 15, which is the length of my filename.

You can see the whole project [here](https://github.com/yringler/rabbi-gordon-audio).
I attempt to download [in the media service](https://github.com/yringler/rabbi-gordon-audio/blob/master/src/app/shared/services/lesson-media.service.ts).

Here's my versions (from tns doctor)
√ Component nativescript has 5.3.0 version and is up to date.
√ Component tns-core-modules has 5.3.1 version and is up to date.
√ Component tns-android has 5.3.0 version and is up to date.

My version of the downloader: (from package-lock.json):
        "nativescript-downloader": {
            "version": "2.1.4",
            "resolved": "https://registry.npmjs.org/nativescript-downloader/-/nativescript-downloader-2.1.4.tgz",
            "integrity": "sha512-WWa0U43FzD3K8a/+4JxKo1W1FT8X7IjMeSiWtLLjZ+NN33FoMYXz4l9xf6xGYBAiEcc71xVlh7LFnuIvrQ60vA=="
        }


Here's my exception:
An uncaught Exception occurred on "OkHttp Dispatcher" thread.
java.lang.StringIndexOutOfBoundsException: length=15; index=-1
	at java.lang.String.substring(String.java:1935)
	at co.fitcom.fancydownloader.ManagerService$2$1.onResponse(ManagerService.java:141)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

Thank you for this plugin! If the problem is specifying path and name, I might experiment with leaving those out and moving the file where I want after.
I'll try taking a look at the java files.

**Comment by yringler** [comment]
Update: I worked around by not specifying the file name, and then renaming it after the download is finished.

[Here's the commit](https://github.com/yringler/rabbi-gordon-audio/commit/52f254c71ef8f7b761dc67e65ff5465cdd40d89e) where I put in the workaround.

I would still love to try to fix the bug in the plugin, but now that I have a workaround it isn't as high priority 🙈
Isn't that the way of things.

**Comment by wendt88** [comment]
wow it seems one of the worst plugins for NS.
wrong readme, a lot of breaking bugs, and it never gets an update.
And this is verified?
It works if you ignore the docu and if you need to place a file somewhere xD

**Comment by yringler** [comment]
In general nativescript has never really caught on like other cross platform solutions.
One symptom is that there aren't that many great plugins which are being actively worked on by an active community (read, zero).
Although a fantastic product, and I enjoyed testing it out in a project, I've ultimately stopped using it, and [switched](https://github.com/yringler/inside-app) to [flutter](https://flutter.dev/docs/get-started/install), whose community is jaw droppingly active. There are a plethora of incredible plugins, with lots of active people behind them, sometimes doing mindblowing things. Performance is out of this world, and getting better.
The biggest problem I had, when I was looking at a sql ORM (I don't need one yet, but will soon), is that there are a bunch of high quality, well supported options, with active communities behind them.

Flutter uses dart, not javascript. Some people consider that bad, but it hasn't kept flutter from taking off. Probably because dart is AWESOME!
Personally, I think the whole concept of making sophisticated programs with html/javascript is really bad, and JS in particular is just a flat out terrible language, and I'd avoid it like the plague if I could.
Yes, if you have to use JS, typescript is great, but ultimately the types are very shallow, they aren't enforced by the runtime.

**Comment by andipahlevy** [comment]
how to fix this issue?

**Comment by triniwiz** [comment]
This will be fixed in the next release , I'm currently working through my plugins list worked on ~3 randomly before deciding to do it alphabetically so currently on a. 😂

**Comment by andipahlevy** [comment]
> This will be fixed in the next release , I'm currently working through my plugins list worked on ~3 randomly before deciding to do it alphabetically so currently on a. 😂

ok thanks bro. for now, i can handle it with rename method. Thanks for your hard work
